site_name: Zumo Labs Documentation
site_description: 'Create, Generate, and Iterate Synthetic Data.'
site_url: 'https://zpy.github.io/'
repo_name: 'zumolabs/zpy'
repo_url: 'https://github.com/ZumoLabs/zpy'
copyright: 'Copyright &copy; 2021 Zumo Labs'
site_dir: 'docs'

theme:
  name: material
  features:
    - navigation.tabs
    - tabs
    - instant
  palette:
    primary: light blue
    accent: orange
  font: 
    text: Consolas
  logo: assets/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - site/overrides/.icons

nav:
  - Home: index.md
  - Overview:
    - Why use Synthetic Data: overview/why.md
    - Does it Work?: overview/work.md
    - Workflow:
        - sim: overview/sim.md
        - cli: overview/cli.md
        - webapp: overview/webapp.md
    - Training with Synthetic Data: overview/training.md
  - Zpy:
    - Install:
        - script: zpy/install/script.md
        - pip: zpy/install/pip.md
        - linux developer: zpy/install/linux.md
        - windows developer: zpy/install/windows.md
    - Script Templates: zpy/template.md
    - Running Sim: zpy/sim.md
    - Segmentation Images: zpy/segmentation.md
    - Depth Images: zpy/depth.md
    - Jittering Object Pose: zpy/jitterpose.md
    - Jitering Materials: zpy/jittermat.md
    - Random HDRI Backgrounds: zpy/hdri.md
  - CLI:
    - zpy: cli/zpy.md
    - zpy login: cli/login.md
    - zpy list: cli/list.md
    - zpy get: cli/get.md
    - zpy upload: cli/upload.md
    - zpy create: cli/create.md
    - zpy logs: cli/logs.md
  - Web App:
    - images: app/images.md
    - experiments: app/experiments.md
  - Blender Addon: zpy/addon.md
  - Releases:
    - v1.2: releases/1.2-NOTES.md
