name: lint-push

on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  run-linters:
    name: Format Python with black
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install black

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_name: "Lint Bot"
          git_email: "infra@zumolabs.ai"
          auto_fix: true # auto commit style fixes
          black: true
          flake8: false
